### ISSUE TITLE
Rows not properly aligned with L4731 !?

### ISSUE THREAD

**Issue by jdelker** [tmaier/asn-qr-code-label-generator#4]
Thanks @tmaier for this surpisingly simple but highly effective method to print ASN labels!
Please don't get offended by the title. I'm quite confident, that you have testet this, but it doesn't work here and I would like to get to the bottom of it ;)

When I startet to print the first labels (on Avery L4731 forms), I encountered a missalignment of the rows.
The first label in a row matched, but each succeeding label lacked a tiny bit, adding up to approx 2-3mm offset on the last label in the row.
The spacing on the vertical rows looked good, though.

At first, I suspected the printer driver (Brother) - and in fact #1 indicates, that there may be issues - but besides some eventually required adjustments of page margins, I could not find any (scaling) problem with the driver.
To rule that component out, I let Chrome print directly to PDF (not via the printer driver!) to be able to verify what is actually generated.
I used the rulers and helper lines of "PDF Xchange Viewer" to exactly measure the placements of the elements in the PDF - and somehwat surprisingly they matched my manual measurements of the printout!

Ok, given that, I now dived into your HTML/CSS code. While I'm certainly no expert in that matter, I tried to follow the formating directions: (Please correct me, if I got something wrong)
- Each element is 25.4mm wide ( `w-[25.4mm]`)
- Between each element is a gap of 2.5mm (`gap-x-[2.5mm]`)
- Calculating the distance from the left edge of the first to the last element would then by 6 * 25.4 + 6 *2.5 = **167.4mm**.

All that matches my measurements of the Avery L4731 form! So all good there, obviously.

Now, if I perform the same measurements on the generated PDF, I got this:
- The distance between the left edge of first and last element is only ~**165mm**
- The difference accounts exactly for the offset-skew seen on the printouts.

I would conclude that there is some rendering issue of the page in Chrome!?
I've attached the generated PDF for your reference.
[asn_orig-tmaier.pdf](https://github.com/tmaier/asn-qr-code-label-generator/files/15093984/asn_orig-tmaier.pdf)

Any thoughts welcome.

**Comment by touraner** [comment]
Did the same experience today on my MAC. Maybe it works different on Windows?

**Comment by tmaier** [comment]
I am working on Mac. I had a very very small deviation on the last box and I accounted this on my printer for inaccuracy of the printer. So the Mac is not the issue.

lets do one thing to de-bug it: download the word file from https://www.avery.co.uk/template-l4731

<img width="389" alt="image" src="https://github.com/tmaier/asn-qr-code-label-generator/assets/350038/ee322c49-1375-49d6-a171-c1ae4006ae5b">
This menu give you the size information.

You will see that WIDTHxHIGH is 2,54 cm X 1 cm
You will see that the margin between two boxes is 0,25 cm (see `3,64-(0,85+2,54)` for the first two boxes)

This are the numbers we are using here in the code:
<img width="691" alt="image" src="https://github.com/tmaier/asn-qr-code-label-generator/assets/350038/dd70dea2-b601-405b-b82f-ea7fab3f2474">

I re-read now how how the box model works at https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

and essentially it is `width + padding + border`, not just `width`. This means, I will change this now, so that padding and border does not affect it anymore. I hope this helps.

I would ask you to re-check the vertical positioning of the boxes

**Comment by tmaier** [comment]
I updated now https://tobiasmaier.info/asn-qr-code-label-generator/

Please review this

**Comment by jdelker** [comment]
Vertical alignment is ok.
Horizontal alignment is still off. The total distance between first and last element (each left edge) still does not add up to 167,4mm. (6*25,4+6*2,5) but is more like 166mm.

[asn_orig-tmaier2.pdf](https://github.com/tmaier/asn-qr-code-label-generator/files/15113091/asn_orig-tmaier2.pdf)

**Comment by TimberlAndRE-de** [comment]
I have the same problem, the horizontal alignment is (now) off for me too.
It worked until last print out. The alignment wasn't perfectly centered inside each sticker but it was ok.
but today I wanted to print the next sheet with the next 186 numbers but now the prints in the two right columns of stickers are all off the sticker borders for at least 1mm...
I guess something was changed in the past weeks?

**Comment by TimberlAndRE-de** [comment]
I tried older versions of your tool now and it's still off
So it seems the change wasn't in your tool but in the browser (or the way it renders the css/html) maybe?


here's an example of my print out:
![20240429_173126](https://github.com/tmaier/asn-qr-code-label-generator/assets/67441153/d3a5c099-2047-4957-8516-e48ba94292f3)

**Comment by jdelker** [comment]
> lets do one thing to de-bug it: download the word file from https://www.avery.co.uk/template-l4731

FYI: If I print that template, the fields align perfectly with the Avery L4731 form. So it's obviously no issue with the printer driver, but the rendering of the browser.

**Comment by jdelker** [comment]
I believe to have found the problem and the cure.
See my PR #5.

**Comment by TimberlAndRE-de** [comment]
Yay !! this works perfectly!

It's working with the commit version you mentioned (not with the latest version) and your changes

Thank you so much!

**Comment by tmaier** [comment]
I merged the changes of #5. And I am going to close this issue. Please re-open, if the problem persists
